name: Github Actions

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        container: reactnativecommunity/react-native-android
        steps:
            - uses: actions/checkout@v2
            - name: Envinfo
              run: npx envinfo
            - name: Install dependencies
              run: npm install
            - name: Create credentials
              run: sudo chmod +x scripts/write-app-config.js && sudo npm run write:config
            - name: Run jetifier
              run: npx jetify
            - name: Build application
              run: yarn install && cd android && chmod +x gradlew && ./gradlew assembleDebug
